/*
  Views propostas para analytics de jornada comercial:
  Orcamento -> Pedido -> Nota Fiscal

  Baseadas nas tabelas:
  - ORCAMENTO
  - ITEM_ORC
  - PED_VENDA
  - ITEM_PED_VENDA
  - NOTA_FISCAL
  - ITEM_NF

  Observacoes:
  - A view de cabecalho usa o vinculo ITEM_ORC -> PED_VENDA.
  - A view por produto agrega antes por pedido+produto para evitar fan-out.
  - Cancelamento de NF pode variar por tenant; validar o texto real de NFCancelada.
*/

CREATE OR ALTER VIEW dbo.VW_SWIA_ORCAMENTO_JORNADA
AS
WITH OrcamentoBase AS (
    SELECT
        O.EmpCod AS CODEMPRESA,
        O.OrcNum AS ORCAMENTO,
        O.OrcData AS EMISSAO_ORCAMENTO,
        O.EntCod AS CLIENTE_CODIGO,
        O.OrcEntNome AS CLIENTE,
        O.OrcEntNomeFant AS NOMEFANTASIA,
        O.OrcUsuCodAtend AS VENDEDOR,
        O.StatOrcCod AS STATUS_CODIGO,
        O.OrcStatResult AS STATUS_DESCRICAO,
        CAST(ISNULL(O.OrcValTotal, 0) AS decimal(18, 2)) AS VALOR_ORCADO
    FROM dbo.ORCAMENTO O
),
PedidoPorOrcamento AS (
    SELECT
        IO.EmpCod AS CODEMPRESA,
        IO.OrcNum AS ORCAMENTO,
        COUNT(DISTINCT PV.PedVendaNum) AS QTD_PEDIDOS,
        MIN(PV.PedVendaData) AS PRIMEIRA_DATA_PEDIDO,
        MAX(PV.PedVendaData) AS ULTIMA_DATA_PEDIDO,
        CAST(SUM(ISNULL(PV.PedVendaValTotal, 0)) AS decimal(18, 2)) AS VALOR_PEDIDO
    FROM dbo.ITEM_ORC IO
    INNER JOIN dbo.PED_VENDA PV
        ON PV.EmpCod = ISNULL(NULLIF(IO.ItOrcEmpCodPedVenda, ''), IO.EmpCod)
       AND PV.PedVendaNum = IO.PedVendaNum
    GROUP BY
        IO.EmpCod,
        IO.OrcNum
),
NotaPorOrcamento AS (
    SELECT
        IO.EmpCod AS CODEMPRESA,
        IO.OrcNum AS ORCAMENTO,
        COUNT(DISTINCT CONCAT(NF.EmpCod, ':', NF.CtrlDFModForm, ':', NF.CtrlDFSerie, ':', NF.NFNum)) AS QTD_NOTAS,
        MIN(NF.NFDataEmis) AS PRIMEIRA_DATA_FATURAMENTO,
        MAX(NF.NFDataEmis) AS ULTIMA_DATA_FATURAMENTO,
        CAST(SUM(ISNULL(NF.NFValTotNota, 0)) AS decimal(18, 2)) AS VALOR_FATURADO
    FROM dbo.ITEM_ORC IO
    INNER JOIN dbo.PED_VENDA PV
        ON PV.EmpCod = ISNULL(NULLIF(IO.ItOrcEmpCodPedVenda, ''), IO.EmpCod)
       AND PV.PedVendaNum = IO.PedVendaNum
    INNER JOIN dbo.NOTA_FISCAL NF
        ON NF.EmpCod = PV.EmpCod
       AND NF.NFPedVenda = PV.PedVendaNum
    WHERE UPPER(LTRIM(RTRIM(ISNULL(NF.NFCancelada, 'NAO')))) NOT IN ('SIM', 'S', 'TRUE', 'CANCELADA')
    GROUP BY
        IO.EmpCod,
        IO.OrcNum
)
SELECT
    O.CODEMPRESA,
    O.ORCAMENTO,
    O.EMISSAO_ORCAMENTO,
    O.CLIENTE_CODIGO,
    O.CLIENTE,
    O.NOMEFANTASIA,
    O.VENDEDOR,
    O.STATUS_CODIGO,
    O.STATUS_DESCRICAO,
    O.VALOR_ORCADO,
    ISNULL(P.QTD_PEDIDOS, 0) AS QTD_PEDIDOS,
    P.PRIMEIRA_DATA_PEDIDO,
    P.ULTIMA_DATA_PEDIDO,
    ISNULL(P.VALOR_PEDIDO, 0) AS VALOR_PEDIDO,
    ISNULL(N.QTD_NOTAS, 0) AS QTD_NOTAS,
    N.PRIMEIRA_DATA_FATURAMENTO,
    N.ULTIMA_DATA_FATURAMENTO,
    ISNULL(N.VALOR_FATURADO, 0) AS VALOR_FATURADO,
    CASE
        WHEN P.PRIMEIRA_DATA_PEDIDO IS NULL OR O.EMISSAO_ORCAMENTO IS NULL THEN NULL
        ELSE DATEDIFF(DAY, O.EMISSAO_ORCAMENTO, P.PRIMEIRA_DATA_PEDIDO)
    END AS DIAS_ATE_PRIMEIRO_PEDIDO,
    CASE
        WHEN N.PRIMEIRA_DATA_FATURAMENTO IS NULL OR O.EMISSAO_ORCAMENTO IS NULL THEN NULL
        ELSE DATEDIFF(DAY, O.EMISSAO_ORCAMENTO, N.PRIMEIRA_DATA_FATURAMENTO)
    END AS DIAS_ATE_PRIMEIRO_FATURAMENTO,
    CASE
        WHEN N.PRIMEIRA_DATA_FATURAMENTO IS NULL OR P.PRIMEIRA_DATA_PEDIDO IS NULL THEN NULL
        ELSE DATEDIFF(DAY, P.PRIMEIRA_DATA_PEDIDO, N.PRIMEIRA_DATA_FATURAMENTO)
    END AS DIAS_PEDIDO_ATE_FATURAMENTO,
    CAST(CASE WHEN ISNULL(P.QTD_PEDIDOS, 0) > 0 THEN 1 ELSE 0 END AS bit) AS CONVERTEU_EM_PEDIDO,
    CAST(CASE WHEN ISNULL(N.QTD_NOTAS, 0) > 0 THEN 1 ELSE 0 END AS bit) AS CONVERTEU_EM_FATURAMENTO
FROM OrcamentoBase O
LEFT JOIN PedidoPorOrcamento P
    ON P.CODEMPRESA = O.CODEMPRESA
   AND P.ORCAMENTO = O.ORCAMENTO
LEFT JOIN NotaPorOrcamento N
    ON N.CODEMPRESA = O.CODEMPRESA
   AND N.ORCAMENTO = O.ORCAMENTO;
GO

CREATE OR ALTER VIEW dbo.VW_SWIA_ORCAMENTO_JORNADA_PRODUTO
AS
WITH OrcamentoProduto AS (
    SELECT
        IO.EmpCod AS CODEMPRESA,
        IO.OrcNum AS ORCAMENTO,
        IO.ProdCodEstr AS CODIGOITEM,
        MAX(COALESCE(NULLIF(IO.ItOrcProdNome, ''), NULLIF(IO.ItOrcNomeProd, ''), NULLIF(IO.ItOrcNomeProdAlt, ''))) AS ITEM,
        MIN(O.OrcData) AS EMISSAO_ORCAMENTO,
        COUNT(DISTINCT IO.PedVendaNum) AS QTD_PEDIDOS_REFERENCIADOS,
        CAST(SUM(ISNULL(IO.ItOrcQtd, 0)) AS decimal(24, 9)) AS QUANTIDADE_ORCADA,
        CAST(SUM(COALESCE(IO.ItOrcValFinal, IO.ItOrcValTot, 0)) AS decimal(18, 2)) AS VALOR_ORCADO
    FROM dbo.ITEM_ORC IO
    INNER JOIN dbo.ORCAMENTO O
        ON O.EmpCod = IO.EmpCod
       AND O.OrcNum = IO.OrcNum
    GROUP BY
        IO.EmpCod,
        IO.OrcNum,
        IO.ProdCodEstr
),
PedidoProduto AS (
    SELECT
        IPV.EmpCod AS CODEMPRESA_PEDIDO,
        IPV.PedVendaNum,
        IPV.ProdCodEstr AS CODIGOITEM,
        MIN(PV.PedVendaData) AS PRIMEIRA_DATA_PEDIDO,
        MAX(PV.PedVendaData) AS ULTIMA_DATA_PEDIDO,
        CAST(SUM(ISNULL(IPV.ItPedVendaQtd, 0)) AS decimal(24, 9)) AS QUANTIDADE_PEDIDA,
        CAST(SUM(COALESCE(IPV.ItPedVendaValFinal, IPV.ItPedVendaValTot, 0)) AS decimal(18, 2)) AS VALOR_PEDIDO,
        COUNT(*) AS QTD_LINHAS_PEDIDO
    FROM dbo.ITEM_PED_VENDA IPV
    INNER JOIN dbo.PED_VENDA PV
        ON PV.EmpCod = IPV.EmpCod
       AND PV.PedVendaNum = IPV.PedVendaNum
    GROUP BY
        IPV.EmpCod,
        IPV.PedVendaNum,
        IPV.ProdCodEstr
),
NotaProduto AS (
    SELECT
        IPV.EmpCod AS CODEMPRESA_PEDIDO,
        IPV.PedVendaNum,
        IPV.ProdCodEstr AS CODIGOITEM,
        COUNT(DISTINCT CONCAT(NF.EmpCod, ':', NF.CtrlDFModForm, ':', NF.CtrlDFSerie, ':', NF.NFNum)) AS QTD_NOTAS,
        MIN(NF.NFDataEmis) AS PRIMEIRA_DATA_FATURAMENTO,
        MAX(NF.NFDataEmis) AS ULTIMA_DATA_FATURAMENTO,
        CAST(SUM(ISNULL(INF.ItNFQtd, 0)) AS decimal(24, 9)) AS QUANTIDADE_FATURADA,
        CAST(SUM(COALESCE(INF.ItNFValTotFinal, INF.ItNFValTot, 0)) AS decimal(18, 2)) AS VALOR_FATURADO
    FROM dbo.ITEM_PED_VENDA IPV
    INNER JOIN dbo.NOTA_FISCAL NF
        ON NF.EmpCod = IPV.EmpCod
       AND NF.CtrlDFModForm = IPV.CtrlDFModForm
       AND NF.CtrlDFSerie = IPV.CtrlDFSerie
       AND NF.NFNum = IPV.NFNum
    LEFT JOIN dbo.ITEM_NF INF
        ON INF.EmpCod = IPV.EmpCod
       AND INF.CtrlDFModForm = IPV.CtrlDFModForm
       AND INF.CtrlDFSerie = IPV.CtrlDFSerie
       AND INF.NFNum = IPV.NFNum
       AND INF.ItNFSeq = IPV.ItNFSeq
    WHERE UPPER(LTRIM(RTRIM(ISNULL(NF.NFCancelada, 'NAO')))) NOT IN ('SIM', 'S', 'TRUE', 'CANCELADA')
    GROUP BY
        IPV.EmpCod,
        IPV.PedVendaNum,
        IPV.ProdCodEstr
),
VinculoOrcPedidoProduto AS (
    SELECT DISTINCT
        IO.EmpCod AS CODEMPRESA,
        IO.OrcNum AS ORCAMENTO,
        IO.ProdCodEstr AS CODIGOITEM,
        ISNULL(NULLIF(IO.ItOrcEmpCodPedVenda, ''), IO.EmpCod) AS CODEMPRESA_PEDIDO,
        IO.PedVendaNum
    FROM dbo.ITEM_ORC IO
    WHERE IO.PedVendaNum IS NOT NULL
)
SELECT
    OP.CODEMPRESA,
    OP.ORCAMENTO,
    OP.CODIGOITEM,
    OP.ITEM,
    OP.EMISSAO_ORCAMENTO,
    OP.QUANTIDADE_ORCADA,
    OP.VALOR_ORCADO,
    COUNT(DISTINCT V.PedVendaNum) AS QTD_PEDIDOS,
    MIN(PP.PRIMEIRA_DATA_PEDIDO) AS PRIMEIRA_DATA_PEDIDO,
    MAX(PP.ULTIMA_DATA_PEDIDO) AS ULTIMA_DATA_PEDIDO,
    CAST(SUM(ISNULL(PP.QUANTIDADE_PEDIDA, 0)) AS decimal(24, 9)) AS QUANTIDADE_PEDIDA,
    CAST(SUM(ISNULL(PP.VALOR_PEDIDO, 0)) AS decimal(18, 2)) AS VALOR_PEDIDO,
    CAST(SUM(ISNULL(NP.QTD_NOTAS, 0)) AS int) AS QTD_NOTAS,
    MIN(NP.PRIMEIRA_DATA_FATURAMENTO) AS PRIMEIRA_DATA_FATURAMENTO,
    MAX(NP.ULTIMA_DATA_FATURAMENTO) AS ULTIMA_DATA_FATURAMENTO,
    CAST(SUM(ISNULL(NP.QUANTIDADE_FATURADA, 0)) AS decimal(24, 9)) AS QUANTIDADE_FATURADA,
    CAST(SUM(ISNULL(NP.VALOR_FATURADO, 0)) AS decimal(18, 2)) AS VALOR_FATURADO,
    CASE
        WHEN MIN(PP.PRIMEIRA_DATA_PEDIDO) IS NULL OR OP.EMISSAO_ORCAMENTO IS NULL THEN NULL
        ELSE DATEDIFF(DAY, OP.EMISSAO_ORCAMENTO, MIN(PP.PRIMEIRA_DATA_PEDIDO))
    END AS DIAS_ATE_PRIMEIRO_PEDIDO,
    CASE
        WHEN MIN(NP.PRIMEIRA_DATA_FATURAMENTO) IS NULL OR OP.EMISSAO_ORCAMENTO IS NULL THEN NULL
        ELSE DATEDIFF(DAY, OP.EMISSAO_ORCAMENTO, MIN(NP.PRIMEIRA_DATA_FATURAMENTO))
    END AS DIAS_ATE_PRIMEIRO_FATURAMENTO
FROM OrcamentoProduto OP
LEFT JOIN VinculoOrcPedidoProduto V
    ON V.CODEMPRESA = OP.CODEMPRESA
   AND V.ORCAMENTO = OP.ORCAMENTO
   AND ISNULL(V.CODIGOITEM, '') = ISNULL(OP.CODIGOITEM, '')
LEFT JOIN PedidoProduto PP
    ON PP.CODEMPRESA_PEDIDO = V.CODEMPRESA_PEDIDO
   AND PP.PedVendaNum = V.PedVendaNum
   AND ISNULL(PP.CODIGOITEM, '') = ISNULL(V.CODIGOITEM, '')
LEFT JOIN NotaProduto NP
    ON NP.CODEMPRESA_PEDIDO = V.CODEMPRESA_PEDIDO
   AND NP.PedVendaNum = V.PedVendaNum
   AND ISNULL(NP.CODIGOITEM, '') = ISNULL(V.CODIGOITEM, '')
GROUP BY
    OP.CODEMPRESA,
    OP.ORCAMENTO,
    OP.CODIGOITEM,
    OP.ITEM,
    OP.EMISSAO_ORCAMENTO,
    OP.QUANTIDADE_ORCADA,
    OP.VALOR_ORCADO;
GO
